spring:
  application:
    name: application
  config:
    import: "configserver:http://localhost:8888"
  cloud:
    config:
      fail-fast: true  # Остановить приложение, если Config Server недоступен